# Generated by Django 4.2 on 2023-04-24 03:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categoria", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("isDelete", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="EstadoCredito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estadoCredito", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("isDelete", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="EstadoPedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("estadoPedido", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("isDelete", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Pedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("isDelete", models.BooleanField()),
                (
                    "estado_pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="root.estadopedido",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("direccion", models.TextField()),
                ("telefonoFijo", models.CharField(max_length=15)),
                ("whatsapp", models.CharField(max_length=15)),
                ("e_mail", models.CharField(max_length=50)),
                ("web_site", models.CharField(max_length=100)),
                ("hora_inicio", models.TimeField()),
                ("hora_fin", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("isDelete", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="TipoPago",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipoPago", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("isDelete", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="TipoTienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipoTienda", models.CharField(max_length=15)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("isDelete", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Venta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto_vendido", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fecha_venta", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("isDelete", models.BooleanField()),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="root.pedido"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User_Tienda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("isDelete", models.BooleanField()),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="root.tienda"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tienda",
            name="idTipoTienda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="root.tipotienda"
            ),
        ),
        migrations.CreateModel(
            name="registroCodigoAuth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=6)),
                ("fecha", models.DateTimeField()),
                ("isComfirm", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("isDelete", models.BooleanField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50)),
                ("descripcion", models.TextField()),
                ("codigo", models.CharField(max_length=20)),
                ("img_link", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("isDelete", models.BooleanField()),
                ("isPublic", models.BooleanField()),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="root.categoria"
                    ),
                ),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="root.tienda"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pedido",
            name="tienda",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="root.tienda"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="tipo_pago",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="root.tipopago"
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Lote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("fecha_vencimiento", models.DateField()),
                ("precio", models.DecimalField(decimal_places=2, max_digits=5)),
                ("isDelete", models.BooleanField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="root.producto"
                    ),
                ),
                (
                    "tienda",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="root.tienda"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Logs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_hora", models.DateTimeField(auto_now_add=True)),
                ("tipo_evento", models.CharField(max_length=30)),
                ("tabla_afectada", models.CharField(max_length=30)),
                ("descripcion", models.TextField()),
                ("origen", models.CharField(max_length=30)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DetallePedido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("isDelete", models.BooleanField()),
                (
                    "lote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="root.lote"
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="root.pedido"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Credito",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("monto", models.DecimalField(decimal_places=2, max_digits=5)),
                ("fecha_credito", models.DateTimeField()),
                ("plazo_dias", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("isDelete", models.BooleanField()),
                (
                    "estado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="root.estadocredito",
                    ),
                ),
                (
                    "pedido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="root.pedido"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
